[build]
builder = "nixpacks"
startCommand = "cargo build --release"


[deploy]
startCommand = "cargo run --release"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "On-Failure"